theme: jekyll-theme-hacker
title: Valgfaget teknologi og design
description: Nettside utviklet i valgfaget teknologi og design 

<img src="https://github.com/chhaars/chhaars.github.io/blob/main/Bilder/logo.png" alt="Åset" style="float:right;width:150px;height:128px;">
